import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './components/Header'
import Dishes from './components/Dishes'
import Login from './components/Login'
import Register from './components/Register'
import AddDish from './components/AddDish'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Appetite.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="/your-path-to-uicons/css/uicons-rounded-regular.css" rel="stylesheet" />
        <link href="/your-path-to-uicons/css/uicons-rounded-bold.css" rel="stylesheet" />
        <link href="/your-path-to-uicons/css/uicons-rounded-solid.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        {/* <Login/>
        <Register/> */}
        <Dishes/>

        <AddDish/>
      </main>
    </>
  )
}
